export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_MORE_STORIES_SUCCESS = 'FETCH_MORE_STORIES_SUCCESS';
export const FETCH_STORIES_FAILURE = 'FETCH_STORIES_FAILURE';

export const REFRESH_STORIES = 'REFRESH_STORIES';
export const REFRESH_STORIES_SUCCESS = 'REFRESH_STORIES_SUCCESS';
export const REFRESH_STORIES_FAILURE = 'REFRESH_STORIES_FAILURE';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';
export const FETCH_MORE_COMMENTS_SUCCESS = 'FETCH_MORE_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_RESET = 'FETCH_COMMENTS_RESET';

export const FAVORITE_STORY = 'FAVORITE_STORY';
export const UNFAVORITE_STORY = 'UNFAVORITE_STORY';
